version: "3.8"

services:
  app:
    build: 
      context: ./back-end
      dockerfile: Dockerfile_app
    ports: 
      - 3000:3000
    depends_on: 
      - mysql_server
  
  mysql_server:
    image: mysql:8.0
    environment: 
      - MYSQL_DATABASE=forum
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    
