version: "3.8"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - ${BACKEND_PORT_IN}:${BACKEND_PORT_OUT}
    depends_on: 
      - mysql_server
  
  mysql_server:
    image: mysql:8.0
    env_file:
      - ./.env
    environment: 
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    
